
export const localPrompts = ()=>{
    const randomIndex = Math.floor(Math.random() * prompts.length);
    return prompts[randomIndex];
}

const prompts = [
    "A futuristic city with flying cars at sunset",
    "An ancient Bengali village beside a river",
    "A dragon flying over snow-capped mountains",
    "A magical forest with glowing mushrooms",
    "A neon-lit cyberpunk street at night",
    "A spaceship landing on Mars",
    "A child flying a kite in a golden field",
    "An astronaut riding a horse on the moon",
    "A cozy cabin in the woods during snowfall",
    "A warrior princess with a glowing sword",
    "A robot making tea in a traditional kitchen",
    "A giant whale flying through the clouds",
    "A sunset over the sea with birds in silhouette",
    "A steampunk airship flying through thunderstorm",
    "A cat wearing glasses reading a book",
    "A royal Bengal tiger sitting on a golden throne",
    "A mosque under the stars with glowing lights",
    "An alien jungle full of bioluminescent plants",
    "A medieval castle on top of a hill",
    "A wizard casting a spell in a cave",
    "A school of glowing fish under the ocean",
    "A peaceful Japanese garden in spring",
    "A dreamlike floating island in the sky",
    "A cyberpunk woman with glowing eyes",
    "A superhero landing pose on a skyscraper",
    "A haunted mansion in a foggy forest",
    "A mystical tree with glowing leaves",
    "A sandstorm in the desert with camels",
    "A Bengali wedding scene with traditional clothes",
    "A watercolor painting of a village fair",
    "A UFO hovering over a cornfield",
    "A butterfly with rainbow-colored wings",
    "A fantasy creature walking through the fog",
    "A realistic baby dragon sleeping in a nest",
    "A city made of glass towers and sky bridges",
    "A pirate ship sailing through stormy sea",
    "A moonlit night in a Bengali tea garden",
    "A dancer mid-spin in traditional attire",
    "A quiet street after rain with reflections",
    "A futuristic motorcycle chase through neon city",
    "A library floating in the clouds",
    "A picnic under cherry blossom trees",
    "A tiger and a lion facing each other on a cliff",
    "A surreal melting clock on a desert dune",
    "A giant robot standing in a rice field",
    "A cartoon-style kitchen on fire with chaos",
    "A couple walking in the rain under one umbrella",
    "A 3D render of a chocolate city",
    "A superhero dog flying over a city",
    "A baby elephant playing in a mud puddle",
    "A painting of a sleepy town at dawn",
    "A floating temple in the sky above clouds",
    "A ghost train moving through misty hills",
    "A time traveler walking through ancient ruins",
    "A steampunk watch with exposed gears",
    "A robot painting on a canvas",
    "A fairytale castle with rainbow and unicorns",
    "A man sitting alone in a vast desert",
    "A giant sunflower field with children playing",
    "A child discovering a secret door in a tree",
    "A floating Bengali rickshaw in space",
    "A neon Bengali signboard on a rainy street",
    "A tiger-shaped constellation in the night sky",
    "A modern house built inside a giant tree",
    "A cartoon character lost in a supermarket",
    "A spaceship shaped like a banana",
    "A realistic baby panda holding a flower",
    "A cat sleeping on a laptop keyboard",
    "A lone boat in the middle of a foggy lake",
    "A girl with glowing butterflies around her",
    "A sunrise over the Himalayas",
    "A robot drinking tea on a hilltop",
    "A rainbow bridge connecting two planets",
    "A post-apocalyptic Dhaka city",
    "A treehouse made of books",
    "A mother bird feeding her babies in a nest",
    "A street food vendor in a busy market",
    "A dragon curled around a crystal orb",
    "A 3D render of a melting ice cream planet",
    "A musical concert on top of a floating island",
    "A circus in space with zero gravity",
    "A girl flying with balloons over the city",
    "A train running on rainbow tracks",
    "A man opening a glowing treasure chest",
    "A castle made of clouds during sunset",
    "A sleeping fox in a bed of flowers",
    "A mermaid resting on a rock under moonlight",
    "A Bengali fisherman casting net at sunrise",
    "A mystical deer with glowing antlers",
    "A night market full of lanterns and lights",
    "A spaceship built out of recycled junk",
    "A cartoon cow jumping over the moon",
    "A robot and child watching fireworks together",
    "A lost island shaped like a heart",
    "A fantasy map drawn on ancient parchment",
    "A galaxy visible through a giant telescope",
    "A chocolate waterfall in candy land",
    "A knight riding a fire-breathing horse",
    "A desert village with floating buildings",
    "A secret underwater temple with glowing runes",
    "A futuristic version of Old Dhaka",
    "A baby lion learning to roar in the jungle",
    "A 3D clay model of a happy village",
    "A magical Bengali folk tale scene",
    "A tree with doors leading to other worlds",
    "A fox made of fire running through a forest",
];
